Update deploy_airflow_dag.yml

diff --git a/.github/workflows/deploy_airflow_dag.yml b/.github/workflows/deploy_airflow_dag.yml
--- a/.github/workflows/deploy_airflow_dag.yml
+++ b/.github/workflows/deploy_airflow_dag.yml
@@ -1,33 +1,64 @@
 name: Deploy Airflow DAG to Astronomer
 
 on:
+  # Trigger on push or pull request to the `main` branch
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
+  # Trigger manually using workflow_dispatch
+  workflow_dispatch:
+    inputs:
+      deploymentId:
+        description: "Deployment ID"
+        required: true
+        type: string
+      apiToken:
+        description: "Astro API Token"
+        required: true
+        type: string
+
+env:
+  ASTRO_API_TOKEN: ${{ inputs.apiToken || secrets.ASTRO_API_TOKEN }}
+  DEPLOYMENT_ID: ${{ inputs.deploymentId || vars.DEPLOYMENT_ID }}
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
 
     steps:
+      # Checkout the repository
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      # Install the Astronomer CLI
       - name: Install Astronomer CLI
         run: |
           sudo curl -sSL https://install.astronomer.io | sudo bash
           export PATH=$PATH:$HOME/.astro/bin
 
+      # Authenticate with Astronomer
       - name: Authenticate with Astronomer
-        run: echo "eyJhbGciOiJSUzI1NiIsImtpZCI6ImNsb2Q0aGtqejAya3AwMWozdWNqbzJwOHIiLCJ0eXAiOiJKV1QifQ.eyJhcGlUb2tlbklkIjoiY201eXd0YjV2MDczOTAxbmM0d2FwOTUzMyIsImF1ZCI6ImFzdHJvbm9tZXItZWUiLCJpYXQiOjE3MzcwMDY0ODYsImlzQXN0cm9ub21lckdlbmVyYXRlZCI6dHJ1ZSwiaXNJbnRlcm5hbCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vYXBpLmFzdHJvbm9tZXIuaW8iLCJraWQiOiJjbG9kNGhranowMmtwMDFqM3Vjam8ycDhyIiwicGVybWlzc2lvbnMiOlsiYXBpVG9rZW5JZDpjbTV5d3RiNXYwNzM5MDFuYzR3YXA5NTMzIiwiZGVwbG95bWVudElkOmNtNXl1OTJmNjA2cnowMWtoNm91NmZndmIiLCJvcmdhbml6YXRpb25JZDpjbTV3OGRobDcxNHpxMDFsbWlqbWJxZ3JuIiwib3JnU2hvcnROYW1lOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4iLCJ3b3Jrc3BhY2VJZDpjbTV3OGRqMTAxNHp4MDFsbXphazR4MTI5Il0sInNjb3BlIjoiYXBpVG9rZW5JZDpjbTV5d3RiNXYwNzM5MDFuYzR3YXA5NTMzIGRlcGxveW1lbnRJZDpjbTV5dTkyZjYwNnJ6MDFraDZvdTZmZ3ZiIG9yZ2FuaXphdGlvbklkOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4gb3JnU2hvcnROYW1lOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4iLCJzdWIiOiJjbTV3OGN0bmgwZWVjMDFsaHZwaDhmeGFzIiwidmVyc2lvbiI6ImNtNXl3dGI1djA3MzgwMW5jeHEyd24xMmwifQ.rONseJ2LipMeKDC7mJJir6Askgr1TxtoU1JHAArt2dtuhFUUPyoTUSGfvB7rl1PtlH8U9aOFvXPOa9RFy8K4KGD9ybEnqedZtpVXTHBug2lNLIT6JZmcJpgJBAc4WuRDe2G5wypHFX1sDVqg7N7Y6zir6HYDMBHPGcks53WtbAZ-JiVmpyfXgfwrstUD44TsdVgl2tEnMFotMEDk3Eo-FIst6gMXRXSiEwm08tmFAV0K2cLD83VnR3sCuMCkIfNmaGEgsW1Y1PGKt5K0_bo832WDIbd6z0Ci0n1QaL2wyFUULWiKhHrzsyHPwgGdV5TbRIHgLOzt7bag7dYeWoA92w" | astro login --token
+        run: |
+          if [ "${{ env.ASTRO_API_TOKEN }}" == "" ]; then
+            echo "Missing ASTRO_API_TOKEN. Please provide it via workflow inputs or GitHub secrets."
+            exit 1
+          fi
+          echo "${{ env.ASTRO_API_TOKEN }}" | astro login --token
 
+      # Set Astronomer Workspace
       - name: Set Astronomer Workspace
-        run: astro context switch cm5w8dj1014zx01lmzak4x129
+        run: |
+          if [ "${{ env.DEPLOYMENT_ID }}" == "" ]; then
+            echo "Missing DEPLOYMENT_ID. Please provide it via workflow inputs or GitHub environment variables."
+            exit 1
+          fi
+          astro context switch ${{ env.DEPLOYMENT_ID }}
 
+      # Deploy the DAG
       - name: Deploy DAG
         run: |
-          cd path/to/your-astro-project
-          astro deploy cm5yu92f606rz01kh6ou6fgvb
+          cd path/to/your-astro-project # Update this to your Astronomer project path
+          astro deploy ${{ env.DEPLOYMENT_ID }}
